name: cloud-guard-agent
arch: amd64
platform: linux
epoch: 3
version: 1.7.0.0
release: 1
section: default
priority: extra
maintainer: ctc
description: |
  cloud-guard-agent
license: MIT
contents:
  - src: ./cloud-guard-agent.service
    dst: /etc/elkeid/cloud-guard-agent.service
    file_info:
      mode: 0600
      owner: root
      group: root
  - src: ./cloud-guard-agent
    dst: /etc/elkeid/cloud-guard-agent
    file_info:
      mode: 0700
      owner: root
      group: root
  - src: ./scripts/cloud-guard-agent.sysvinit
    dst: /etc/elkeid/cloud-guard-agent.sysvinit
    file_info:
      mode: 0700
      owner: root
      group: root
  - src: ./cloudguardctl
    dst: /etc/elkeid/cloudguardctl
    file_info:
      mode: 0700
      owner: root
      group: root
scripts:
  preinstall: ./scripts/preinstall.sh
  postinstall: ./scripts/postinstall.sh
  preremove: ./scripts/preremove.sh
rpm:
  group: Unspecified
  compression: lzma