# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MQData.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'MQData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cMQData.proto\x12\x07hids_pb\"\xe7\x02\n\x06MQData\x12\x11\n\tdata_type\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x1b\n\x04\x62ody\x18\x03 \x01(\x0b\x32\r.hids_pb.Item\x12\x10\n\x08\x61gent_id\x18\x04 \x01(\t\x12\x14\n\x0cin_ipv4_list\x18\x05 \x01(\t\x12\x14\n\x0c\x65x_ipv4_list\x18\x06 \x01(\t\x12\x14\n\x0cin_ipv6_list\x18\x07 \x01(\t\x12\x14\n\x0c\x65x_ipv6_list\x18\x08 \x01(\t\x12\x10\n\x08hostname\x18\t \x01(\t\x12\x0f\n\x07version\x18\n \x01(\t\x12\x0f\n\x07product\x18\x0b \x01(\t\x12\x16\n\x0eTenantAuthCode\x18\x0c \x01(\t\x12\x10\n\x08TenantID\x18\r \x01(\x05\x12\x0e\n\x06HostID\x18\x0e \x01(\x05\x12\x10\n\x08time_pkg\x18\x0f \x01(\x03\x12\x10\n\x08psm_name\x18\x10 \x01(\t\x12\x10\n\x08psm_path\x18\x11 \x01(\t\x12\x0c\n\x04tags\x18\x12 \x01(\t\"`\n\x04Item\x12)\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x19.hids_pb.Item.FieldsEntry\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\tZ\x07hids_pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MQData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007hids_pb'
  _globals['_ITEM_FIELDSENTRY']._loaded_options = None
  _globals['_ITEM_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_MQDATA']._serialized_start=26
  _globals['_MQDATA']._serialized_end=385
  _globals['_ITEM']._serialized_start=387
  _globals['_ITEM']._serialized_end=483
  _globals['_ITEM_FIELDSENTRY']._serialized_start=438
  _globals['_ITEM_FIELDSENTRY']._serialized_end=483
# @@protoc_insertion_point(module_scope)
